name: Deploy wiki
on:
  workflow_dispatch: null
  push:
    paths:
      - 'wiki/**'
    branches:
      - master
jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push wiki changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_MAIL: ${{ secrets.GH_MAIL }}
        GH_NAME: ${{ github.repository_owner }}
        REPO: https://github.com/EvanMcBroom/lsa-whisperer.wiki.git